import { BangladeshUpazila } from "../bangladeshGeo";

export const CHATTOGRAM_UPAZILAS: BangladeshUpazila[] = [
  // Chattogram
  { id: "kotwali_ctg", districtId: "chattogram", name: "Kotwali", bnName: "কোতোয়ালী", areas: ["Andarkilla", "New Market", "Chawkbazar", "Lalkhan Bazar", "Tiger Pass"] },
  { id: "panchlaish", districtId: "chattogram", name: "Panchlaish", bnName: "পাঁচলাইশ", areas: ["GEC Circle", "Nasirabad", "2 No Gate", "Prabartak", "Khulshi"] },
  { id: "double_mooring", districtId: "chattogram", name: "Double Mooring", bnName: "ডবলমুরিং", areas: ["Agrabad C/A", "Chowmuhani", "Badamtali", "Madarbari"] },
  { id: "pahartali", districtId: "chattogram", name: "Pahartali", bnName: "পাহাড়তলী", areas: ["Wireless", "Saraipara", "Noyabazar", "Alangkar"] },
  { id: "halishahar", districtId: "chattogram", name: "Halishahar", bnName: "হালিশহর", areas: ["Housing Estate", "Boropol", "Noyabazar", "F-Block"] },
  { id: "patenga", districtId: "chattogram", name: "Patenga", bnName: "পতেঙ্গা", areas: ["Airport Road", "Sea Beach", "Katgor", "Steel Mill"] },
  { id: "chandgaon", districtId: "chattogram", name: "Chandgaon", bnName: "চান্দগাঁও", areas: ["Bahaddarhat", "Mohra", "Kalurghat", "Chandgaon R/A"] },
  { id: "hathazari", districtId: "chattogram", name: "Hathazari", bnName: "হাটহাজারী", areas: ["Chittagong University", "Hathazari Bazar", "Fatehabad", "Aman Bazar"] },
  { id: "sitakunda", districtId: "chattogram", name: "Sitakunda", bnName: "সীতাকুণ্ড", areas: ["Bhatiari", "Kumira", "Sitakunda Bazar", "Barabkunda", "Faujdarhat"] },
  { id: "mirsharai", districtId: "chattogram", name: "Mirsharai", bnName: "মীরসরাই", areas: ["Baraiyarhat", "Mirsharai Bazar", "Zorarganj", "Mithachhara"] },
  { id: "patiya", districtId: "chattogram", name: "Patiya", bnName: "পটিয়া", areas: ["Patiya Pourashava", "Kachuai", "Shovon Dandi", "Kusumpura"] },
  { id: "boalkhali", districtId: "chattogram", name: "Boalkhali", bnName: "বোয়ালখালী", areas: ["Gomdandi", "Kandhurkhil", "Shakpura", "Ahla"] },
  { id: "anwara", districtId: "chattogram", name: "Anwara", bnName: "আনোয়ারা", areas: ["CUFL", "Parki Beach", "Chatari", "Boalia"] },
  { id: "raozan", districtId: "chattogram", name: "Raozan", bnName: "রাউজান", areas: ["CUET", "Gohira", "Pahartali", "Noapara"] },
  { id: "rangunia", districtId: "chattogram", name: "Rangunia", bnName: "রাঙ্গুনিয়া" },
  { id: "fatikchhari", districtId: "chattogram", name: "Fatikchhari", bnName: "ফটিকছড়ি" },
  { id: "satkania", districtId: "chattogram", name: "Satkania", bnName: "সাতকানিয়া", areas: ["Keranihat", "Satkania Sadar", "Bazalia", "Eochia"] },
  { id: "lohaghar", districtId: "chattogram", name: "Lohagara", bnName: "লোহাগাড়া", areas: ["Padua", "Amirabad", "Chunti", "Adhunagar"] },
  { id: "sandwip", districtId: "chattogram", name: "Sandwip", bnName: "সন্দ্বীপ" },
  { id: "banshhkhali", districtId: "chattogram", name: "Banshkhali", bnName: "বাঁশখালী" },
  { id: "karnaphuli", districtId: "chattogram", name: "Karnaphuli", bnName: "কর্ণফুলী" },

  // Cox's Bazar
  { id: "coxsbazar_sadar", districtId: "coxs_bazar", name: "Cox's Bazar Sadar", bnName: "কক্সবাজার সদর", areas: ["Kolatoli", "Laboni Beach", "Sugandha", "Jhawtola", "Tekpara", "Ramu Road"] },
  { id: "ramu", districtId: "coxs_bazar", name: "Ramu", bnName: "রামু" },
  { id: "teknaf", districtId: "coxs_bazar", name: "Teknaf", bnName: "টেকনাফ", areas: ["Saint Martin", "Teknaf Port", "Shamlapur"] },
  { id: "ukhiya", districtId: "coxs_bazar", name: "Ukhiya", bnName: "উখিয়া", areas: ["Inani Beach", "Kotupalong", "Balukhali"] },
  { id: "chakaria", districtId: "coxs_bazar", name: "Chakaria", bnName: "চকোরিয়া", areas: ["Chakaria Pourashava", "Dulahazra Safari Park", "Badarkhali"] },
  { id: "pekua", districtId: "coxs_bazar", name: "Pekua", bnName: "পেকুয়া" },
  { id: "kutubdia", districtId: "coxs_bazar", name: "Kutubdia", bnName: "কুতুবদিয়া" },
  { id: "moheshkhali", districtId: "coxs_bazar", name: "Moheshkhali", bnName: "মহেশখালী", areas: ["Gorakghata", "Matarbari", "Adinath"] },
  { id: "eidgaon", districtId: "coxs_bazar", name: "Eidgaon", bnName: "ঈদগাঁও" },

  // Cumilla
  { id: "cumilla_sadar", districtId: "cumilla", name: "Adarsha Sadar", bnName: "আদর্শ সদর", areas: ["Kandirpar", "Ranir Bazar", "Shashangachha", "Kotbari", "Tomsom Bridge"] },
  { id: "sadar_dakshin", districtId: "cumilla", name: "Sadar Dakshin", bnName: "সদর দক্ষিণ", areas: ["Paduar Bazar", "Bijoypur", "Bagmara", "Perul"] },
  { id: "daudkandi", districtId: "cumilla", name: "Daudkandi", bnName: "দাউদকান্দি", areas: ["Gouripur", "Daudkandi Toll Plaza", "Iliotganj", "Pennai"] },
  { id: "chandina", districtId: "cumilla", name: "Chandina", bnName: "চান্দিনা", areas: ["Chandina Bazar", "Madhaiya", "Barkamta", "Dollai"] },
  { id: "burichang", districtId: "cumilla", name: "Burichang", bnName: "বুড়িচং", areas: ["Burichang Bazar", "Mainamati", "Mokam", "Sholonal"] },
  { id: "chauddagram", districtId: "cumilla", name: "Chauddagram", bnName: "চৌদ্দগ্রাম", areas: ["Miapara", "Batisa", "Kashinagar", "Gunabati"] },
  { id: "laksam", districtId: "cumilla", name: "Laksam", bnName: "লাকসাম", areas: ["Laksam Junction", "Dawrat", "Gobindapur", "Kandirpar"] },
  { id: "debidwar", districtId: "cumilla", name: "Debidwar", bnName: "দেবিদ্বার", areas: ["Debidwar Bazar", "Rasulpur", "Gunjar", "Dhamti"] },
  { id: "barura", districtId: "cumilla", name: "Barura", bnName: "বরুড়া" },
  { id: "brahmanpara", districtId: "cumilla", name: "Brahmanpara", bnName: "ব্রাহ্মণপাড়া" },
  { id: "homna", districtId: "cumilla", name: "Homna", bnName: "হোমনা" },
  { id: "muradnagar", districtId: "cumilla", name: "Muradnagar", bnName: "মুরাদনগর" },
  { id: "nangalkot", districtId: "cumilla", name: "Nangalkot", bnName: "নাঙ্গলকোট" },
  { id: "meghna", districtId: "cumilla", name: "Meghna", bnName: "মেঘনা" },
  { id: "titash", districtId: "cumilla", name: "Titash", bnName: "তিতাস" },
  { id: "monohargonj", districtId: "cumilla", name: "Monohargonj", bnName: "মনোহরগঞ্জ" },
  { id: "lalmai", districtId: "cumilla", name: "Lalmai", bnName: "লালমাই" },

  // Feni
  { id: "feni_sadar", districtId: "feni", name: "Feni Sadar", bnName: "ফেনী সদর", areas: ["Feni Town", "Grand Trunk Road", "Masterpara", "Doshani", "Kalipal", "Fazilpur", "Kazirbag"] },
  { id: "daganbhuiyan", districtId: "feni", name: "Daganbhuiyan", bnName: "দাগনভূঞা", areas: ["Daganbhuiyan Bazar", "Chilonia", "Rajapur", "Silonia", "Sindurpur"] },
  { id: "chhagalnaiya", districtId: "feni", name: "Chhagalnaiya", bnName: "ছাগলনাইয়া", areas: ["Chhagalnaiya Pourashava", "Pathannagar", "Radhanagar", "Shuvapur"] },
  { id: "sonagazi", districtId: "feni", name: "Sonagazi", bnName: "সোনাগাজী", areas: ["Sonagazi Bazar", "Mangalkandi", "Motiganj", "Char Chandia", "Chor Dorbesh"] },
  { id: "parshuram", districtId: "feni", name: "Parshuram", bnName: "পরশুরাম", areas: ["Parshuram Bazar", "Mirzanagar", "Boxmahmmud", "Chitholia"] },
  { id: "fulgazi", districtId: "feni", name: "Fulgazi", bnName: "ফুলগাজী", areas: ["Fulgazi Bazar", "Munshirhat", "Dorbarpur", "Anandapur"] },

  // Brahmanbaria
  { id: "brahmanbaria_sadar", districtId: "brahmanbaria", name: "Brahmanbaria Sadar", bnName: "ব্রাহ্মণবাড়িয়া সদর", areas: ["Kandipara", "Medda", "Kautoli", "Bhadughar"] },
  { id: "ashuganj", districtId: "brahmanbaria", name: "Ashuganj", bnName: "আশুগঞ্জ", areas: ["Ashuganj Power Station", "Kharampur", "Tarua"] },
  { id: "sarail", districtId: "brahmanbaria", name: "Sarail", bnName: "সরাইল", areas: ["Sarail Bazar", "Biswa Road", "Shahbazpur", "Panishwar"] },
  { id: "kasba", districtId: "brahmanbaria", name: "Kasba", bnName: "কসবা", areas: ["Kasba Pourashava", "Kuti", "Binauti", "Gopinathpur"] },
  { id: "akhaura", districtId: "brahmanbaria", name: "Akhaura", bnName: "আখাউড়া", areas: ["Land Port", "Gangasagar", "Mogra", "Maniond"] },
  { id: "nabinagar", districtId: "brahmanbaria", name: "Nabinagar", bnName: "নবীনগর" },
  { id: "bancharampur", districtId: "brahmanbaria", name: "Bancharampur", bnName: "বাঞ্ছারামপুর" },
  { id: "nasirnagar", districtId: "brahmanbaria", name: "Nasirnagar", bnName: "নাসিরনগর" },
  { id: "bijoynagar", districtId: "brahmanbaria", name: "Bijoynagar", bnName: "বিজয়নগর" },

  // Noakhali
  { id: "noakhali_sadar", districtId: "noakhali", name: "Noakhali Sadar (Sudharam)", bnName: "নোয়াখালী সদর", areas: ["Maijdee Court", "Sonapur", "Datterhat"] },
  { id: "begumganj", districtId: "noakhali", name: "Begumganj", bnName: "বেগমগঞ্জ", areas: ["Chowmuhani", "Maijdee Road", "Mirwarishpur", "Rajganj"] },
  { id: "senbagh", districtId: "noakhali", name: "Senbagh", bnName: "সেনবাগ", areas: ["Senbagh Bazar", "Kankirhat", "Sebarhat", "Chhatarpaia"] },
  { id: "chatkhil", districtId: "noakhali", name: "Chatkhil", bnName: "চাটখিল", areas: ["Chatkhil Bazar", "Khilpara", "Badalkot", "Shahapur"] },
  { id: "companiganj_noakhali", districtId: "noakhali", name: "Companiganj", bnName: "কোম্পানীগঞ্জ", areas: ["Basurhat", "Chor Elahi", "Chor Fakira", "Rampur"] },
  { id: "hatiya", districtId: "noakhali", name: "Hatiya", bnName: "হাতিয়া" },
  { id: "subarnachar", districtId: "noakhali", name: "Subarnachar", bnName: "সুবর্ণচর" },
  { id: "kabirhat", districtId: "noakhali", name: "Kabirhat", bnName: "কবিরহাট" },
  { id: "sonaimuri", districtId: "noakhali", name: "Sonaimuri", bnName: "সোনাইমুড়ী" },

  // Chandpur
  { id: "chandpur_sadar", districtId: "chandpur", name: "Chandpur Sadar", bnName: "চাঁদপুর সদর", areas: ["Boro Station", "Puran Bazar", "Natun Bazar", "Baborhat"] },
  { id: "hajiganj", districtId: "chandpur", name: "Hajiganj", bnName: "হাজীগঞ্জ" },
  { id: "matlab_dakshin", districtId: "chandpur", name: "Matlab Dakshin", bnName: "মতলব দক্ষিণ" },
  { id: "matlab_uttar", districtId: "chandpur", name: "Matlab Uttar", bnName: "মতলব উত্তর" },
  { id: "shahrasti", districtId: "chandpur", name: "Shahrasti", bnName: "শাহরাস্তি" },
  { id: "faridganj", districtId: "chandpur", name: "Faridganj", bnName: "ফরিদগঞ্জ" },
  { id: "kachua_chandpur", districtId: "chandpur", name: "Kachua", bnName: "কচুয়া" },
  { id: "haimchar", districtId: "chandpur", name: "Haimchar", bnName: "হাইমচর" },

  // Lakshmipur
  { id: "lakshmipur_sadar", districtId: "lakshmipur", name: "Lakshmipur Sadar", bnName: "লক্ষ্মীপুর সদর" },
  { id: "raipur", districtId: "lakshmipur", name: "Raipur", bnName: "রায়পুর" },
  { id: "ramganj", districtId: "lakshmipur", name: "Ramganj", bnName: "রামগঞ্জ" },
  { id: "ramgati", districtId: "lakshmipur", name: "Ramgati", bnName: "রামগতি" },
  { id: "kamalnagar", districtId: "lakshmipur", name: "Kamalnagar", bnName: "কমলনগর" },

  // Rangamati
  { id: "rangamati_sadar", districtId: "rangamati", name: "Rangamati Sadar", bnName: "রাঙ্গামাটি সদর" },
  { id: "kaptai", districtId: "rangamati", name: "Kaptai", bnName: "কাপ্তাই" },
  { id: "kawkhali_rangamati", districtId: "rangamati", name: "Kawkhali (Betbunia)", bnName: "কাউখালী" },
  { id: "baghaichhari", districtId: "rangamati", name: "Baghaichhari (Sajek)", bnName: "বাঘাইছড়ি (সাজেক)" },
  { id: "barkal", districtId: "rangamati", name: "Barkal", bnName: "বরকল" },
  { id: "langadu", districtId: "rangamati", name: "Langadu", bnName: "লংগদু" },
  { id: "rajasthali", districtId: "rangamati", name: "Rajasthali", bnName: "রাজস্থলী" },
  { id: "belaichhari", districtId: "rangamati", name: "Belaichhari", bnName: "বিলাইছড়ি" },
  { id: "juraichhari", districtId: "rangamati", name: "Juraichhari", bnName: "জুরাইছড়ি" },
  { id: "naniarchar", districtId: "rangamati", name: "Naniarchar", bnName: "নানিয়ারচর" },

  // Bandarban
  { id: "bandarban_sadar", districtId: "bandarban", name: "Bandarban Sadar", bnName: "বান্দরবান সদর" },
  { id: "thanchi", districtId: "bandarban", name: "Thanchi", bnName: "থানচি" },
  { id: "rowangchhari", districtId: "bandarban", name: "Rowangchhari", bnName: "রোয়াংছড়ি" },
  { id: "ruma", districtId: "bandarban", name: "Ruma (Boga Lake)", bnName: "রুমা" },
  { id: "lama", districtId: "bandarban", name: "Lama", bnName: "লামা" },
  { id: "alikadam", districtId: "bandarban", name: "Alikadam", bnName: "আলীকদম" },
  { id: "naikhongchhari", districtId: "bandarban", name: "Naikhongchhari", bnName: "নাইক্ষ্যংছড়ি" },

  // Khagrachhari
  { id: "khagrachhari_sadar", districtId: "khagrachhari", name: "Khagrachhari Sadar", bnName: "খাগড়াছড়ি সদর" },
  { id: "dighinala", districtId: "khagrachhari", name: "Dighinala", bnName: "দিঘীনালা" },
  { id: "panchhari", districtId: "khagrachhari", name: "Panchhari", bnName: "পানছড়ি" },
  { id: "mahalchhari", districtId: "khagrachhari", name: "Mahalchhari", bnName: "মহালছড়ি" },
  { id: "matiranga", districtId: "khagrachhari", name: "Matiranga", bnName: "মাটিরাঙ্গা" },
  { id: "manikchhari", districtId: "khagrachhari", name: "Manikchhari", bnName: "মানিকছড়ি" },
  { id: "ramgarh", districtId: "khagrachhari", name: "Ramgarh", bnName: "রামগড়" },
  { id: "lakshmichhari", districtId: "khagrachhari", name: "Lakshmichhari", bnName: "লক্ষ্মীছড়ি" },
  { id: "guimara", districtId: "khagrachhari", name: "Guimara", bnName: "গুইমারা" },
];
